# Generated by Django 5.0.4 on 2024-05-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playbills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playbill",
            name="description",
        ),
        migrations.RemoveField(
            model_name="playbill",
            name="location",
        ),
        migrations.AlterField(
            model_name="playbill",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="playbill",
            name="price",
            field=models.CharField(max_length=100),
        ),
    ]
