# Generated by Django 5.0.4 on 2024-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "playbills",
            "0002_remove_playbill_description_remove_playbill_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="playbill",
            name="link",
            field=models.URLField(default="https://gatob.kz/#tab05_2024"),
        ),
        migrations.AlterField(
            model_name="playbill",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="playbill",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="playbill",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
