# Generated by Django 5.0.4 on 2024-05-21 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playbills", "0003_playbill_link_alter_playbill_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playbill",
            name="link",
        ),
    ]
