# Generated by Django 5.0.4 on 2024-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playbills", "0004_remove_playbill_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbill",
            name="image",
            field=models.ImageField(default="", upload_to="playbill_images/"),
        ),
    ]
